---
version: "3"

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  mysql:
    image: mysql:5.7.24
    environment:
      - MYSQL_DATABASE=recognizer_test
      - MYSQL_ROOT_PASSWORD=recognizer
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
    ports:
      - "3306:3306"
