---
version: "3"

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_PASSWORD: system76
      MYSQL_DATABASE: recognizer_test
      MYSQL_ROOT_PASSWORD: recognizer
      MYSQL_ROOT_HOST: "%"
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
      - --sql-mode=STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION
    volumes:
      - ../mysql_data:/var/lib/mysql        
    ports:
      - "3306:3306"
